---
# =================================================================================================
# Areas
# =================================================================================================
- name: area/docker
  color: "0e8a16"
- name: area/github
  color: "0e8a16"
- name: area/code
  color: "0e8a16"
