---
fullnameOverride: external-dns-mikrotik

logLevel: debug
policy: sync
sources: ["ingress", "service"]
interval: 1s
txtOwnerId: default
txtPrefix: k8s.
domainFilters: ["example.com"]

provider:
  name: webhook
  webhook:
    image:
      repository: ghcr.io/mirceanton/external-dns-provider-mikrotik
      tag: pr-97
      pullPolicy: Always
    env:
      - name: LOG_FORMAT
        value: json
      - name: LOG_LEVEL
        value: debug
      - name: MIKROTIK_BASEURL
        valueFrom:
          secretKeyRef:
            name: mikrotik-credentials
            key: MIKROTIK_BASEURL
      - name: MIKROTIK_USERNAME
        valueFrom:
          secretKeyRef:
            name: mikrotik-credentials
            key: MIKROTIK_USERNAME
      - name: MIKROTIK_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mikrotik-credentials
            key: MIKROTIK_PASSWORD
      - name: MIKROTIK_SKIP_TLS_VERIFY
        valueFrom:
          secretKeyRef:
            name: mikrotik-credentials
            key: MIKROTIK_SKIP_TLS_VERIFY

    livenessProbe:
      httpGet:
        path: /healthz
        port: http-webhook
      initialDelaySeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /readyz
        port: http-webhook
      initialDelaySeconds: 10
      timeoutSeconds: 5

extraArgs:
  - --ignore-ingress-tls-spec
  - --source=crd
  - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
  - --crd-source-kind=DNSEndpoint
  - --managed-record-types=A
  - --managed-record-types=AAAA
  - --managed-record-types=CNAME
  - --managed-record-types=TXT
  - --managed-record-types=MX
  - --managed-record-types=SRV
  - --managed-record-types=NS

rbac:
  create: true
  additionalPermissions:
    - apiGroups: ["externaldns.k8s.io"]
      resources: ["dnsendpoints"]
      verbs: ["get", "watch", "list"]
    - apiGroups: ["externaldns.k8s.io"]
      resources: ["dnsendpoints/status"]
      verbs: ["*"]
