---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: invalid-record
spec:
  endpoints:
    - dnsName: invalid.example.com
      recordTTL: 180
      recordType: AAAA
      targets:
        - 2001:db8::2
      providerSpecific:
        - name: regexp
          value: ".*"
