---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: regexp-record
spec:
  endpoints:
    - dnsName:
      recordTTL: 180
      recordType: A
      targets:
        - 4.5.6.7
      providerSpecific:
        - name: regexp
          value: "*.regex.example.com"
        - name: comment
          value: "This is a comment"
        - name: address-list
          value: "1.2.3.1"
        - name: match-subdomain
          value: "true"
        - name: disabled
          value: "false"
