---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment2
spec:
  replicas: 3 # Number of desired pods
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: test
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nginx2.example.com
    external-dns.alpha.kubernetes.io/ttl: "600"
    external-dns.alpha.kubernetes.io/webhook-comment: "This is a comment"
    external-dns.alpha.kubernetes.io/webhook-address-list: "1.2.3.4"
    external-dns.alpha.kubernetes.io/webhook-match-subdomain: "true"
    external-dns.alpha.kubernetes.io/webhook-regexp: "test*"
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx2
  type: NodePort
