---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: srv-record
spec:
  endpoints:
    - dnsName: _minecraft._tcp.mc.example.com
      recordTTL: 180
      recordType: SRV
      targets:
        - "0 1 25565 mc.example.com"