---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  # Manual Trigger
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry Run
        required: false
        default: false
        type: boolean

  # "Wet" Run on any push to the main branch that modified a go-related file
  push:
    branches: ["main", "master"]
    paths:
      - "go.mod"
      - "go.sum"
      - "**/**.go"

jobs:
  git:
    if: github.repository_owner == 'mirceanton' #?don't run on forks
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-release-semver.yaml@e3a95ef75601e0b811d0e3f1b9afc04a175acb22 # v3.6.0
    secrets: inherit
    with:
      dry-run: ${{ inputs.dry-run || github.event_name == 'pull_request' }}
