---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Goreleaser

on:
  # Manual Trigger
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry Run
        required: false
        default: false
        type: boolean

  # "Wet" Run on any tag push
  push:
    tags: ["*"]

jobs:
  goreleaser:
    if: github.repository_owner == 'mirceanton' #?don't run on forks
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-go-release.yaml@9ce913356128f964413b5fe99efe4858e18d7831 # v3.4.51
    secrets: inherit
    with:
      dry-run: ${{ inputs.dry-run || github.event_name == 'pull_request' }}
