---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  golangci-lint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-go-lint.yaml@c60bb9813e634b15663d4ff01027e3b32102aef4 # v3.7.2
    with:
      golangci-version: v1.64.3

  yamllint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-yamllint.yaml@c60bb9813e634b15663d4ff01027e3b32102aef4 # v3.7.2
  actionlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-actionlint.yaml@c60bb9813e634b15663d4ff01027e3b32102aef4 # v3.7.2
  shellcheck:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-shellcheck.yaml@c60bb9813e634b15663d4ff01027e3b32102aef4 # v3.7.2
  markdownlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-markdownlint.yaml@c60bb9813e634b15663d4ff01027e3b32102aef4 # v3.7.2
  commitlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-commitlint.yaml@c60bb9813e634b15663d4ff01027e3b32102aef4 # v3.7.2
