---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - '.devcontainer/**'
      - 'README.md'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Create Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: "${{ steps.app-token.outputs.token }}"
