---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test

on:
  # Manual Trigger
  workflow_dispatch: {}

  # Run on any PR
  pull_request: {}

jobs:
  test:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-go-test.yaml@c60bb9813e634b15663d4ff01027e3b32102aef4 # v3.7.2
    secrets: inherit
    with:
      go-version: stable
